CMakeLists: fix build failure by removing -pie from shared library targets
With CMake 4.1.0 the build of libipmctl started failing with:

  error: undefined reference to `main` in *.S

- `-pie` is only valid when linking executables (PIE), not shared
  libraries.
- When applied to a shared library, the linker expects a `main`
  symbol, causing the undefined reference error.
- Remove `-pie` from shared libraries linker flag

Signed-off-by: Yogesh Tyagi <yogesh.tyagi@intel.com>